### ISSUE TITLE
Add possibility to implements customs contract functions 

### ISSUE THREAD

**Issue by J-Ibarra** [horizontalsystems/ethereum-kit-ios#72]
Be able to make extensions to the classes needed to implement contract methods easily

**Comment by ealymbaev** [comment]
We are currently dividing our EthereumKit into two parts.

First part is EthereumKit itself, that can be able to work with Ethereum network only, without implementing any definite smart contracts, but it will be able to provide all the required API for any smart contracts. Moreover it will be able to work in both "http API" and "Light node" modes.
It will provide all the required access to blocks, transactions, smart contracts states and Ethereum storage.

Second part is Erc20Kit, that will provide all the required features for interacting with Erc20 tokens. It will use EthereumKit for interacting with blockchain.

Thus you will able to use EthereumKit API in order to create interactions features for any smart contract you like.

**Comment by ealymbaev** [comment]
We have finished implementing separate Erc20Kit and therefore EthereumKit now supports interaction with smart contracts. For now Ethereum kits supports:

- get logs in blocks range by address and topics filter
- get storage of any smart contract by storage position
- send transaction with custom input

As an example usage you can refer to Erc20Kit that uses both methods above for getting token balance and transactions history and also sending Erc20 token transaction.

**Comment by J-Ibarra** [comment]
Implement on Android too! XD
